config/routes.rb
Dine::Application.routes.draw do

  resources :orderlists
  resources :shoplists
  resources :categories

  get "home/index"

  resources :pins
  resources :pin 
  
  devise_for :users
  match 'users/:id' => 'users#show', as: :user

 
  root :to => 'pins#index'
  get 'usering' => 'users#index'
  get 'detail' => 'users#detail'
  get 'manage' => 'orderlists#manage'
  get 'admin' => 'pages#admin'
  get 'return' => 'pages#return'
  get 'faq' => 'pages#faq'
  get 'why' => 'pages#why'
  get 'service' => 'pages#service'
	get 'privacy' => 'pages#privacy'
  get 'menu' => 'pages#menu'
  get 'recipies' => 'pages#recipies'  
  get 'know' => 'pages#know'
  get 'give' => 'pages#give' 
  get 'how' => 'pages#how' 
  get 'dish1' => 'pages#dish1'
  get 'dish2' => 'pages#dish2' 
  get 'dish3' => 'pages#dish3' 
  get 'dish4' => 'pages#dish4'
  get 'dish5' => 'pages#dish5' 
  get 'dish6' => 'pages#dish6'
  get 'account' => 'pages#account' 
  get 'donations' => 'pages#donations' 
  get 'delivery' => 'pages#delivery'
  get 'hunger' => 'pages#hunger'
  get 'dogood' => 'pages#dogood'
  get 'lovemeal' => 'pages#lovemeal'
  get 'help' => 'pages#help'
  get 'about' => 'pages#about'
  get 'line' => 'pages#line'
  get 'side' => 'pages#side'
  get 'fruit' => 'pages#fruit'
  get 'hocv' => 'pages#hocv'
  get 'chefs' => 'pages#chefs'
  get 'goodcompany' => 'pages#goodcompany'
  get 'hoc' => 'pages#hoc'
  get 'chef29tv' => 'pages#chef29tv'
  get 'makemoney' => 'pages#makemoney'
  get 'orderpage' => 'pages#orderpage'
  get 'pickup' => 'pages#pickup'
  get 'dogooder' => 'pages#dogooder'
  get 'onmenu' => 'pages#onmenu'

  

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  match 'alert' => 'alert#new', :as => 'alert',  :via => :get
  match 'alert'  => 'alert#create', :as => 'alert', :via => :post

  match 'wineordercontact' => 'wineordercontact#new', :as => 'wineordercontact', :via => :get
  match 'wineordercontact' => 'wineordercontact#create', :as => 'wineordercontact', :via => :post

  as :user do
  match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end
  devise_for :users, :controllers => { :confirmations => "confirmations" }

end

app/models/user.rb
class User < ActiveRecord::Base
	extend FriendlyId
  friendly_id :name, use: :slugged

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :confirmable, :rememberable, :trackable, :validatable

 has_attached_file :image, styles: { medium: "180x180>"}
 validates :address, presence: true
 validates :phone, presence: true


  # Setup accessible (or protected) attributes for your model
  attr_accessible :image, :image_file_name, :email, :password, :password_confirmation, :remember_me, :name, :address, :phone, :intro, :dish1, :dish2, :dish3
   # attr_accessible :title, :body

  has_many :pins, :dependent => :destroy
  has_many :orderlists, :dependent => :destroy

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authenticate_user!, except: [:show]
http_basic_authenticate_with name: "admin", password: "mattenzo", except: [:show]


def index
@users = User.all
@users = User.order("created_at desc")
end

def detail
 @orderlists = Orderlist.order("created_at desc").page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orderlists }
    end
  end


  def show
    @user = User.find(params[:id])
    @pins = @user.pins.page(params[:page]).per_page(100)
    @pins = @user.pins.where(user_id: @user.id).order("created_at DESC")
    @pins = @pins.paginate(:page => params[:page], :per_page => 30)
    @orderlists = @user.orderlists.page(params[:page]).per_page(100)
    @orderlists = @user.orderlists.where(user_id: @user.id).order("created_at DESC")
   
  end
 end

 def userorder
    @user = User.find(params[:id])
    @pins = @user.pins.page(params[:page]).per_page(100)
    @pins = @user.pins.where(user_id: @user.id).order("created_at DESC")
    @pins = @pins.paginate(:page => params[:page], :per_page => 30)
    @orderlists = @user.orderlists.page(params[:page]).per_page(100)
    @orderlists = @user.orderlists.where(user_id: @user.id).order("created_at DESC")
   
  end

def userorders
    @user = User.find(params[:id])
    @pins = @user.pins.page(params[:page]).per_page(100)
    @pins = @user.pins.where(user_id: @user.id).order("created_at DESC")
    @pins = @pins.paginate(:page => params[:page], :per_page => 30)
    @orderlists = @user.orderlists.page(params[:page]).per_page(100)
    @orderlists = @user.orderlists.where(user_id: @user.id).order("created_at DESC")
   
  end


def pin_params
   params.require(:user).permit(:description, :image)
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/Welcome.html.erb
Welcome to EEDD-吃吃喝喝

app/views/users/_order.html.erb
<tr>

	<td><%= orderlist.id %></td>
	<td> <%= orderlist.created_at %></td>
	<td> <%= link_to orderlist.user.name, orderlist.user%></td>
	<td> <%= link_to orderlist.user.email, orderlist.user%></td>
	<td><%= link_to '訂單細節', orderlist %></td>


  
</tr>

app/views/users/_user.html.erb
<tr>

	<td><%= user.id %></td>
	<td><%= user.name %></td>
	<td><%= user.email %></td>
	<td><%= user.created_at %></td>
	<td><%= user.phone %></td>
	<td><%= user.address %></td>
	

	
 
</tr>

app/views/users/detail.html.erb
<br><br>
    <font size="5" color ="gray" face = "Baskerville Old Face">所有訂單</font>
    <hr>
     <table class="table table-striped">
        <thead>
            <tr>
               <font size="2" color ="gray" face = "Baskerville Old Face"> <th>會員 #</th></font>
                <th>姓名</th>
                <th>訂購人</th>
                <th>訂購人EMAIL</th>
                <th>查看訂單</th>
                <th>取消訂單</th>
                
            </tr>
        </thead>

    <br>
    <div id="orders">
        <%= render @orders %>
    </div>
       
</table>

app/views/users/index.html.erb
<center>
 <font color="gray" size ="5" face = "Baskerville Old Face">
<%= link_to '新增 Pins+', new_pin_path %> |
<%= link_to '所有會員', usering_path %> |
<%= link_to "所有訂單", manage_path %> |
<a href="http://www.chef29.com/categories/new" >新增分類</a>

</center></font>
<br>



<br><br>
    <font size="5" color ="gray" face = "Baskerville Old Face">所有會員</font>
    <hr>
     <table class="table table-striped">
        <thead>
            <tr>
               <font size="2" color ="gray" face = "Baskerville Old Face">

                <th>會員 ID</th></font>
                <th>姓名</th>
                <th>EMAIL</th>
                <th>成為會員</th>
                <th>電話</th>
                <th>送餐地址</th>
              
               
                
            </tr>
        </thead>

    <br>
    <div id="users">
        <%= render @users %>
    </div>
    
       
</table>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>

<head>
<% content_for :head do %>
    <meta property="fb:app_id"          content="41421303274749826" /> 
    <meta property="og:type"            content="website" /> 
     <meta property="og:url"             content='<% "http://wwww.thechefstars.com/" + user_path(@user) %>' /> 
    <meta property="og:title" content='<%= @user.name %>' />
    <meta property="og:description" content='<%= @user.intro %>' />
    
<% end %>

<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript" src="http://s.sharethis.com/loader.js"></script>
</head>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
     <%= image_tag @user.image %>
    </div>
    
   <div class="span10">
   <font color="gray"  size="5"><b><%= @user.name %></b></font><br>
   <br>
   
   <font color="gray" size="3"><i> <%= simple_format@user.intro %></i></font><br>


    </div>
  </div>
</div>


<hr>
<br>

<div id="pins">
  <%= render @pins %>
</div>

<%= will_paginate @pins %>



<script type="text/javascript">stLight.options({publisher: "3d6bd212-1a1c-4bf7-9f1c-7154d13f873d", doNotHash: false, doNotCopy: false, hashAddressBar: true});</script>
<script>

var options={ "publisher": "3d6bd212-1a1c-4bf7-9f1c-7154d13f873d", "position": "left", "ad": { "visible": false, "openDelay": 5, "closeDelay": 0}, "chicklets": { "items": ["facebook", "twitter", "linkedin", "pinterest", "email", "googleplus", "blogger", "wordpress", "baidu"]}};
var st_hover_widget = new sharethis.widgets.hoverbuttons(options);
</script>
</html>

app/views/users/show.js.erb
$boxes = $('<%= j render(@pins) %>')

$('#pins').append( $boxes ).imagesLoaded( function(){
    $('#pins').masonry( 'reload');
});
<% if @pins.next_page %>
    $('.pagination').replaceWith('<%= j will_paginate(@pins) %>');
<% else %>
    $('.pagination').remove();
<% end %>

app/views/users/userorder.html.erb
<!DOCTYPE html>
<html>

<head>
<% content_for :head do %>
    <meta property="fb:app_id"          content="41421303274749826" /> 
    <meta property="og:type"            content="website" /> 
     <meta property="og:url"             content='<% "http://wwww.thechefstars.com/" + user_path(@user) %>' /> 
    <meta property="og:title" content='<%= @user.name %>' />
    <meta property="og:description" content='<%= @user.intro %>' />
    <meta property="og:image" content='<%= @user.image %>' />
<% end %>


<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript" src="http://s.sharethis.com/loader.js"></script>
</head>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
     <%= image_tag @user.image %>
    </div>
    
    
   <div class="span10">
   <font color="gray"  size="5"><b><%= @user.name %></b></font><br>
   <br>
   <% if @user.intro.present? %>
   <font color="gray" size="3"><i> <%= simple_format@user.intro %></i></font><br>
  
   <% if @user.phone.present? %>
   <font color="gray" size="2"><b>地址:</b> <%= @user.address %></font><br>

   <% else %>
   <% end %>
   
   <% if @user.phone.present? %>
   <font color="gray" size="2"><b>電話: </b> <%= @user.phone %></font><br>
   <% else %>
   <% end %>
   <% else %>
   <br><br>
   <font color="#5CA5FF" size="4" color><i> “您可以在右上角選單個人 > 編輯資料裡填入自我/店家介紹，地址，電話等資訊。”</i></font>
<% end %>

    </div>
  </div>
</div>


<hr>
<br>

<div id="pins">
  <%= render @orderlists %>
</div>

<%= will_paginate @orderlists %>


<script type="text/javascript">stLight.options({publisher: "3d6bd212-1a1c-4bf7-9f1c-7154d13f873d", doNotHash: false, doNotCopy: false, hashAddressBar: true});</script>
<script>
var options={ "publisher": "3d6bd212-1a1c-4bf7-9f1c-7154d13f873d", "position": "left", "ad": { "visible": false, "openDelay": 5, "closeDelay": 0}, "chicklets": { "items": ["facebook", "twitter", "linkedin", "pinterest", "email", "googleplus", "blogger", "wordpress", "baidu"]}};
var st_hover_widget = new sharethis.widgets.hoverbuttons(options);
</script>
</html>

app/views/users/userorders.html.erb
<!DOCTYPE html>
<html>

<head>
<% content_for :head do %>
    <meta property="fb:app_id"          content="41421303274749826" /> 
    <meta property="og:type"            content="website" /> 
     <meta property="og:url"             content='<% "http://wwww.thechefstars.com/" + user_path(@user) %>' /> 
    <meta property="og:title" content='<%= @user.name %>' />
    <meta property="og:description" content='<%= @user.intro %>' />
    <meta property="og:image" content='<%= @user.image %>' />
<% end %>


<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript" src="http://s.sharethis.com/loader.js"></script>
</head>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
     <%= image_tag @user.image %>
    </div>
    
    
   <div class="span10">
   <font color="gray"  size="5"><b><%= @user.name %></b></font><br>
   <br>
   <% if @user.intro.present? %>
   <font color="gray" size="3"><i> <%= simple_format@user.intro %></i></font><br>
  
   <% if @user.phone.present? %>
   <font color="gray" size="2"><b>地址:</b> <%= @user.address %></font><br>

   <% else %>
   <% end %>
   
   <% if @user.phone.present? %>
   <font color="gray" size="2"><b>電話: </b> <%= @user.phone %></font><br>
   <% else %>
   <% end %>
   <% else %>
   <br><br>
   <font color="#5CA5FF" size="4" color><i> “您可以在右上角選單個人 > 編輯資料裡填入自我/店家介紹，地址，電話等資訊。”</i></font>
<% end %>

    </div>
  </div>
</div>


<hr>
<br>

<div id="pins">
  <%= render @orderlists %>
</div>

<%= will_paginate @orderlists %>


<script type="text/javascript">stLight.options({publisher: "3d6bd212-1a1c-4bf7-9f1c-7154d13f873d", doNotHash: false, doNotCopy: false, hashAddressBar: true});</script>
<script>
var options={ "publisher": "3d6bd212-1a1c-4bf7-9f1c-7154d13f873d", "position": "left", "ad": { "visible": false, "openDelay": 5, "closeDelay": 0}, "chicklets": { "items": ["facebook", "twitter", "linkedin", "pinterest", "email", "googleplus", "blogger", "wordpress", "baidu"]}};
var st_hover_widget = new sharethis.widgets.hoverbuttons(options);
</script>
</html>