config/routes.rb
Dine::Application.routes.draw do

  resources :orderlists
  resources :shoplists
  resources :categories

  get "home/index"

  resources :pins
  resources :pin 
  
  devise_for :users
  match 'users/:id' => 'users#show', as: :user

 
  root :to => 'pins#index'
  get 'usering' => 'users#index'
  get 'detail' => 'users#detail'
  get 'manage' => 'orderlists#manage'
  get 'admin' => 'pages#admin'
  get 'return' => 'pages#return'
  get 'faq' => 'pages#faq'
  get 'why' => 'pages#why'
  get 'service' => 'pages#service'
	get 'privacy' => 'pages#privacy'
  get 'menu' => 'pages#menu'
  get 'recipies' => 'pages#recipies'  
  get 'know' => 'pages#know'
  get 'give' => 'pages#give' 
  get 'how' => 'pages#how' 
  get 'dish1' => 'pages#dish1'
  get 'dish2' => 'pages#dish2' 
  get 'dish3' => 'pages#dish3' 
  get 'dish4' => 'pages#dish4'
  get 'dish5' => 'pages#dish5' 
  get 'dish6' => 'pages#dish6'
  get 'account' => 'pages#account' 
  get 'donations' => 'pages#donations' 
  get 'delivery' => 'pages#delivery'
  get 'hunger' => 'pages#hunger'
  get 'dogood' => 'pages#dogood'
  get 'lovemeal' => 'pages#lovemeal'
  get 'help' => 'pages#help'
  get 'about' => 'pages#about'
  get 'line' => 'pages#line'
  get 'side' => 'pages#side'
  get 'fruit' => 'pages#fruit'
  get 'hocv' => 'pages#hocv'
  get 'chefs' => 'pages#chefs'
  get 'goodcompany' => 'pages#goodcompany'
  get 'hoc' => 'pages#hoc'
  get 'chef29tv' => 'pages#chef29tv'
  get 'makemoney' => 'pages#makemoney'
  get 'orderpage' => 'pages#orderpage'
  get 'pickup' => 'pages#pickup'
  get 'dogooder' => 'pages#dogooder'
  get 'onmenu' => 'pages#onmenu'

  

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  match 'alert' => 'alert#new', :as => 'alert',  :via => :get
  match 'alert'  => 'alert#create', :as => 'alert', :via => :post

  match 'wineordercontact' => 'wineordercontact#new', :as => 'wineordercontact', :via => :get
  match 'wineordercontact' => 'wineordercontact#create', :as => 'wineordercontact', :via => :post

  as :user do
  match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end
  devise_for :users, :controllers => { :confirmations => "confirmations" }

end

app/models/orderlist.rb
class Orderlist < ActiveRecord::Base
  attr_accessible :pickupdates, :pickuplocation, :week, :month, :description, :dish1, :gift, :re, :ship, :discount, :paylater, :detail, :reciever, :account, :wireamount, :dish2, :dish3, :dish4, :dish5, :dish6, :dishsum, :time, :phone, :address
 

  belongs_to :user

  validates :dish1, presence: true
  validates :dish2, presence: true
  validates :dish3, presence: true  
  validates :dish4, presence: true
  validates :dish5, presence: true
  validates :dish6, presence: true  
  validates :week, presence: true
  validates :month, presence: true 
  
end 
 

app/controllers/orderlists_controller.rb
class OrderlistsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show, :manage]
  http_basic_authenticate_with name: "admin", password: "mattenzo", except: [:index, :show, :new, :edit, :create, :update, :destroy ]
  # GET /orderlists
  # GET /orderlists.json
  def index
    @orderlists = Orderlist.order("created_at desc").page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orderlists }
    end
  end
  
  def manage
   
    @orderlists = Orderlist.all
    @allorders = Orderlist.order

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @allorders }
    end
  end

  # GET /orderlists/1
  # GET /orderlists/1.json
  def show
    @orderlist = Orderlist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @orderlist }
    end
  end

  # GET /orderlists/new
  # GET /orderlists/new.json
  def new
    @orderlist = current_user.orderlists.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @orderlist }
    end
  end

  # GET /orderlists/1/edit
  def edit
    @orderlist =current_user.orderlists.find(params[:id])
  end

  # POST /orderlists
  # POST /orderlists.json
  def create
    @orderlist = current_user.orderlists.new(params[:orderlist])

    respond_to do |format|
      if @orderlist.save
        format.html { redirect_to @orderlist, notice: '訂單成功送出' }
        format.json { render json: @orderlist, status: :created, location: @orderlist }
      else
        format.html { render action: "new" }
        format.json { render json: @orderlist.errors, status: :unprocessable_entity }
      end
    end
  end


  # PUT /orderlists/1
  # PUT /orderlists/1.json
  def update
    @orderlist = current_user.orderlists.find(params[:id])

    respond_to do |format|
      if @orderlist.update_attributes(params[:orderlist])
        format.html { redirect_to @orderlist, notice: '完成訂單更新' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @orderlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orderlists/1
  # DELETE /orderlists/1.json
  def destroy
    @orderlist = current_user.orderlists.find(params[:id])
    @orderlist.destroy

    respond_to do |format|
      format.html { redirect_to orderlists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/orderlists_helper.rb
module OrderlistsHelper
end

app/views/orderlists/_allorders.html.erb
 <tr>
 
 		<td><%= orderlist.id %></td>
 		<td> <%= orderlist.created_at %></td>
 		<td> <%= link_to orderlist.user.name, orderlist.user%></td>
 		<td> <%= link_to orderlist.user.email, orderlist.user%></td>
 		
        <td><%= link_to 'Show', orderlist %></td>
         <td><%= link_to '刪除', orderlist, method: :delete, data: { confirm: '你確定嗎?' } %></td>
        
  </tr>

  

app/views/orderlists/_orderlist.html.erb
<tr>
<% if current_user == orderlist.user %>


<td><%= orderlist.id %></td>

<td> <%= link_to orderlist.user.name, orderlist.user%></td>
<td> <%= orderlist.user.phone%></td>
<td> <%= orderlist.user.address %></td>
<td><%= orderlist.gift %></td>
<td><%= orderlist.address %></td>
<td><%= orderlist.dish1 %></td>
<td><%= orderlist.dish2 %></td>
<td><%= orderlist.dish3 %></td>
<td><%= orderlist.dish4 %></td>
<td><%= orderlist.dish5 %></td>
<td><%= orderlist.dish6 %></td>
<td><%= orderlist.week %></td>
<td><%= orderlist.month %></td>
<td><%= link_to '查看', orderlist %></td>
<td><%= link_to '取消', alert_path %></td>
<td><%= orderlist.paylater %></td>
<td><%= orderlist.time %></td>

<% else %>
<% end %>   
</tr>

app/views/orderlists/edit.html.erb
<br><br>
<font color="gray" size ="6" face = "Baskerville Old Face">編輯餐點訂購單</font><hr>

<%= render 'form' %>

<%= link_to 'Show', @orderlist %> |
<%= link_to 'Back', orderlists_path %>

app/views/orderlists/index.html.erb
<br><br>
    <font size="5" color ="gray" face = "Baskerville Old Face">所有訂單</font>
    <hr>
     <table class="table table-striped">
        <thead>
            <tr>
               <font size="2" color ="gray" face = "Baskerville Old Face"> 
                <th>訂單</th></font>
               
                <th>訂購人</th>
                <th>電話</th>
                <th>原地址</th>
                <th>送禮</th>
                <th>新地址</th>
                <th>1餐</th>
               <th>2餐</th>
               <th>3餐</th>
               <th>4餐</th>
               <th>5餐</th>
               <th>6餐</th>
               <th>周果</th>
               <th>連果</th>
               <th>訂單</th>
                <th>訂單</th>
               
                <th>付款</th>
                <th>收餐</th>
                <th>發票</th>
            </tr>
        </thead>

    <br>
    <div id="orderlists">
        <%= render @orderlists %>
    </div>
       
</table>

app/views/orderlists/manage.html.erb
<h3>Manage - 後台管理</h3><br><br><hr>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>訂單 </th>
                
                <th>訂購人</th>
                <th>電話</th>
                <th>原地址</th>
                <th>送禮</th>
                <th>新地址</th>

                <th>1餐</th>
               <th>2餐</th>
               <th>3餐</th>
               <th>4餐</th>
               <th>5餐</th>
               <th>6餐</th>
               <th>周果</th>
               <th>連果</th>
          
                <th>訂單</th>
                <th>訂單</th>
                <th>付款</th>
                <th>出貨</th>
                 <th>發票</th>
              
               
            </tr>
        </thead>

<%= render 'pages/admin' %>

          <tbody>
            <%= render @allorders %>
        </tbody>
    </table>



    <br />

app/views/orderlists/new.html.erb
<br><br>
 <center>
<font color="red" size ="6" face = "Baskerville Old Face">本產品服務已停止提供。</font></center>
</div>
<br><br><br><br>


<%= render 'form' %>

<%= link_to 'Back', root_path %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44036574-1', 'chef29.com');
  ga('send', 'pageview');

</script>

app/views/orderlists/show.html.erb
<center><div class="page-header">
 <font color="gray" size ="6" face = "Baskerville Old Face">以下為您的訂單</font>
 </center>
   

<div class="row">
  <div class="span10 offset1">
    <div class="well">
      <% if current_user == @orderlist.user %>
                <%= link_to '修改訂單(填寫付款完資料／帳號／金額...）', edit_orderlist_path(@orderlist) %> |
            <% end %>
            <%= link_to '上一頁', orderlists_path %><br>
<%= link_to '運費說明', delivery_path %><br>
  <br>
      
 <font size = "3" color= "red">選轉賬（選貨到付款不用理會）：請在完成匯款/轉賬餐點貨款後回來更新 1. 帳號末5碼 2.匯款金額!! (查看訂單>訂單細節>修改訂單(填寫付款完資料／帳號／金額...)>填入1.帳號末5碼 & 2.金額)</font>


 <hr>
           </font>
            <p>訂單編號：
              <%= @orderlist.id %>
            </p>
            
         
            <p>訂購時間：
              <%= @orderlist.created_at %>
            </p>
            <hr>

            <p>訂購人：
              <%= @orderlist.user.name %>
            </p>
         <br>

            <% if @orderlist.user.phone.present? %>
            <p>訂購人電話：
              <%= @orderlist.user.phone %>
            </p>
          <br>
            <% else %>
            <% end %>

            <% if @orderlist.user.address.present? %>
            <p>原送餐地址：
              <%= @orderlist.user.address %>
            </p>
            <br>
            <% else %>
             
            <% end %>

          
             <% if @orderlist.user.phone.present? %>
            <p>訂購人聯絡電話：
              <%= @orderlist.user.phone %>
            </p>
            <br>
            <% else %>
            <% end %>



            <p>訂購人EMAIL：
              <%= @orderlist.user.email %>
            </p>
           
            
            <% if @orderlist.gift.present? %>
            <hr>
              <font size = "3" color= "red">送禮：需先完成付款（包括運費）</font>
              <br><br>
            <p>收禮人：
              <%= @orderlist.gift %>
            </p>
            <% else %>
            <% end %>

            <hr>
              <center><font color="#5CA5FF" size ="4" face = "Baskerville Old Face">宅配送貨</font></center>
             
            <p>收餐人聯絡電話：
            <%= @orderlist.phone %>
            </p>
            
            <p>新指定送餐地址：
              <%= @orderlist.address %>
            </p>

            <p>送餐時間：
              <%= @orderlist.time %>
            </p>


            <hr>
            <center><font color="#5CA5FF" size ="4" face = "Baskerville Old Face">Chef29 取貨點取貨</font></center>

            <p>Chef29 取貨點：
            <%= @orderlist.pickuplocation %>
            </p>

            <p>收餐人聯絡電話：
            <%= @orderlist.pickupdates %>
            </p>


            <hr>
            <center><font color="#5CA5FF" size ="4" face = "Baskerville Old Face">餐點</font></center>

            <p>1號餐：
              <%= @orderlist.dish1 %>份
            </p>
           
 
            <p>2號餐：
              <%= @orderlist.dish2 %>份
            </p>
            

            <p>3號餐：
              <%= @orderlist.dish3 %>份
            </p>

             <p>4號餐：
              <%= @orderlist.dish4 %>份
            </p>
           
 
            <p>5號餐：
              <%= @orderlist.dish5 %>份
            </p>
            

            <p>6號餐：
              <%= @orderlist.dish6 %>份
            </p>


            <hr>
            <center><font color="#5CA5FF" size ="4" face = "Baskerville Old Face">每週水果箱</font></center>

          <br><br>

            <p>單次水果箱訂購：
              (<%= @orderlist.week %>)人份水果箱
            </p>

            <p>連續每週水果箱訂購：
              連續(<%= @orderlist.month %>)週水果箱
            </p>

            <hr>

            <% if @orderlist.dish4.present? %>
            <% if @orderlist.week.present? %>
            <p>總共購買了：
            <%= (@orderlist.dish1 + @orderlist.dish2 + @orderlist.dish3 + @orderlist.dish4 + @orderlist.dish5 + @orderlist.dish6 + @orderlist.week + @orderlist.month) %>份餐點(水果箱)

             </p>
           
            <% else %>
 <p>總共購買了：
            <%= (@orderlist.dish1 + @orderlist.dish2 + @orderlist.dish3 + @orderlist.dish4 + @orderlist.dish5 + @orderlist.dish6 ) %>份餐點(水果箱)
             </p>
            <% end %>
  
            </p>
          
            <% else %>
            <p>總共購買了：
            <%= (@orderlist.dish1 + @orderlist.dish2 + @orderlist.dish3 ) %>份餐點（水果箱）
            </p>
            <% end %>

             <p>付款方式：
              <%= @orderlist.paylater %>
            </p>

             <p>備註：
              <%= @orderlist.detail %>
            </p>
            
            <hr>



            <p> 餐點 + 水果箱（未加運費）＄
            
            <%= ((@orderlist.dish4 + @orderlist.dish5 + @orderlist.dish6+@orderlist.dish1 + @orderlist.dish2 + @orderlist.dish3) *299)+(( @orderlist.week+ @orderlist.month) *399)%>  

            <%= link_to'您願意參加愛心鏈活動，多付一餐 ＄299 送給下個訂餐的客人當禮物嗎？-點入看更多', 'http://www.chef29.com/pins/420-starbucks-paying-it-forward'%></p>


            <font size = "2" color= "red">新會員第一份$299餐點免費：若您第一次溝買，請在以上購買金額扣除＄299。（＄299以外特別餐點不能使用）</font>
<br>
          <br>
        
            <br>
            <p>＊免費餐點密碼：
              <%= @orderlist.discount %>
            </p>

            <hr>
            <font size = "3" color= "red">以下請您在完成餐點付款後再回來填入（查看訂單 > 訂單細節 > 修改訂單)</font>
<br><br>
            <p>匯款/轉帳（帳號末5碼）：
              <%= @orderlist.account %>
            </p>

            <p>匯款/轉帳金額：
              <%= @orderlist.wireamount %>
            </p>

            <p>匯款/轉帳日期：$
              <%= @orderlist.re %>
            </p>

            <hr>
            <p>
            付款帳號(匯款/轉帳）: 迪士洛普有限公司
            <br>
            兆豐國際商業銀行(017)（大安分行）
            帳號： 229-09-03502-2
            </p>
            <br>
            <br>

<head>
  <script type="text/javascript">
var fb_param = {};
fb_param.pixel_id = '6009594778928';
fb_param.value = '0.00';
fb_param.currency = 'TWD';
(function(){
  var fpw = document.createElement('script');
  fpw.async = true;
  fpw.src = '//connect.facebook.net/en_US/fp.js';
  var ref = document.getElementsByTagName('script')[0];
  ref.parentNode.insertBefore(fpw, ref);
})();
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/offsite_event.php?id=6009594778928&amp;value=0&amp;currency=TWD" /></noscript>
</head>


            <% if current_user == @orderlist.user %>
                <%= link_to '(填寫付款完資料／帳號／金額...)', edit_orderlist_path(@orderlist) %> |
            <% end %>
            <%= link_to '上一頁', orderlists_path %>
        </div>
    </div>
</div>


<center><img src="https://farm4.staticflickr.com/3713/14084136049_5d3db85aeb_o.jpg" width="1016" height="800" alt="10572560456_23439626d9_o"></center>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44036574-1', 'chef29.com');
  ga('send', 'pageview');

</script>