config/routes.rb
Dine::Application.routes.draw do

  resources :orderlists
  resources :shoplists
  resources :categories

  get "home/index"

  resources :pins
  resources :pin 
  
  devise_for :users
  match 'users/:id' => 'users#show', as: :user

 
  root :to => 'pins#index'
  get 'usering' => 'users#index'
  get 'detail' => 'users#detail'
  get 'manage' => 'orderlists#manage'
  get 'admin' => 'pages#admin'
  get 'return' => 'pages#return'
  get 'faq' => 'pages#faq'
  get 'why' => 'pages#why'
  get 'service' => 'pages#service'
	get 'privacy' => 'pages#privacy'
  get 'menu' => 'pages#menu'
  get 'recipies' => 'pages#recipies'  
  get 'know' => 'pages#know'
  get 'give' => 'pages#give' 
  get 'how' => 'pages#how' 
  get 'dish1' => 'pages#dish1'
  get 'dish2' => 'pages#dish2' 
  get 'dish3' => 'pages#dish3' 
  get 'dish4' => 'pages#dish4'
  get 'dish5' => 'pages#dish5' 
  get 'dish6' => 'pages#dish6'
  get 'account' => 'pages#account' 
  get 'donations' => 'pages#donations' 
  get 'delivery' => 'pages#delivery'
  get 'hunger' => 'pages#hunger'
  get 'dogood' => 'pages#dogood'
  get 'lovemeal' => 'pages#lovemeal'
  get 'help' => 'pages#help'
  get 'about' => 'pages#about'
  get 'line' => 'pages#line'
  get 'side' => 'pages#side'
  get 'fruit' => 'pages#fruit'
  get 'hocv' => 'pages#hocv'
  get 'chefs' => 'pages#chefs'
  get 'goodcompany' => 'pages#goodcompany'
  get 'hoc' => 'pages#hoc'
  get 'chef29tv' => 'pages#chef29tv'
  get 'makemoney' => 'pages#makemoney'
  get 'orderpage' => 'pages#orderpage'
  get 'pickup' => 'pages#pickup'
  get 'dogooder' => 'pages#dogooder'
  get 'onmenu' => 'pages#onmenu'

  

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  match 'alert' => 'alert#new', :as => 'alert',  :via => :get
  match 'alert'  => 'alert#create', :as => 'alert', :via => :post

  match 'wineordercontact' => 'wineordercontact#new', :as => 'wineordercontact', :via => :get
  match 'wineordercontact' => 'wineordercontact#create', :as => 'wineordercontact', :via => :post

  as :user do
  match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end
  devise_for :users, :controllers => { :confirmations => "confirmations" }

end

app/models/category.rb
class Category < ActiveRecord::Base

	attr_accessible :description, :image 
 
has_attached_file :image, styles: { large: "1400x300>"}
  validates_attachment :image, presence: true,
                            content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                            size: { less_than: 5.megabytes }
  attr_accessible :name
  has_many :pins
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "mattenzo", except: :show
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    @pins = @category.pins.page(params[:page]).per_page(100)
    @pins = @category.pins.where(category_id: @category.id).order("created_at DESC")
    @pins = @pins.paginate(:page => params[:page], :per_page => 60)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
      format.js
    end
  end


  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end


def pin_params
   params.require(:user).permit(:description, :image)
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>


  <div class="form-actions">
    <%= f.input :image, label: "上傳圖片" %>
    </div>

  <div class="form-actions">
    <%= f.button :submit %>
     </div>

>

   
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'show', category %></td>
    <td><%= link_to 'edit', edit_category_path(category) %></td>
  
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h3>New category</h3>
<br>

<<center>
 <font color="gray" size ="5" face = "Baskerville Old Face">
<%= link_to '新增 Pins+', new_pin_path %> |
<%= link_to '所有會員', usering_path %> |
<%= link_to "所有訂單", manage_path %> |
<a href="http://www.chef29.com/categories/new" >新增分類</a>

</center></font>
<br>


</center></font>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44036574-1', 'chef29.com');
  ga('send', 'pageview');

</script>

app/views/categories/show.html.erb
<!DOCTYPE html>
<html>

  <head>
    <% content_for :head do %>
    <meta property="fb:app_id"          content="479820998782220" /> 
    <meta property="og:type"            content="Chef29:post" /> 
    <meta property="og:url"             content='<% "http://wwww.chef29.com/" + category_path(@category) %>' /> 
    <meta property="og:title" content='<%= @category.name %>' />
     <meta property="og:image"           content="http://farm4.staticflickr.com/3761/9730599510_a74ae4585d_o.png" /> 
 
   

  <% end %>
<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript" src="http://s.sharethis.com/loader.js"></script>
</head>

<body>

<p id="notice"><%= notice %></p>

 <center><%= image_tag @category.image %></center>
<br>

<hr>

<center>
<div class="row-fluid">
  
  <div class="span3"  >
    <center>
    
   <a href="http://www.chef29.com/users/sign_up" ><img src="https://farm3.staticflickr.com/2830/13400108224_ede3d928a7.jpg" width="225" height="250" alt="jointoday"></a>

  </center>
</div> 

  <div class="span3">
    <center>
 <a href="http://www.chef29.com/onmenu" ><img src="https://farm4.staticflickr.com/3782/13399873843_4180194a3e.jpg" width="225" height="250" alt="Menu"></a> 
</center>
  </div> 


  <div class="span3">
  <center>
<a href="http://www.chef29.com/how"><img src="https://farm8.staticflickr.com/7279/13400107704_bb215ac8c6.jpg" width="225" height="301" alt="howtobuy"></a>

</center>
  </div>

   <div class="span3"><center>
  <a href="http://www.chef29.com/orderpage" ><img src="https://farm4.staticflickr.com/3798/13399751675_49fea54123.jpg" width="225" height="380" alt="kart"></a>
</center>

  </div>

</div>

</center>


<br><br>
  <div id="pins">
     <%= render @pins %>
 </div>

<%= will_paginate @pins %>

<%= link_to '', edit_category_path(@category) %> 
<%= link_to '', categories_path %>

</body>


<br><br><br>

<center>
<div class="row-fluid">
  
  <div class="span3"  >
    <center>
    
   <a href="http://www.chef29.com/users/sign_up" ><img src="https://farm3.staticflickr.com/2830/13400108224_ede3d928a7.jpg" width="225" height="250" alt="jointoday"></a>

  </center>
</div> 

  <div class="span3">
    <center>
 <a href="http://www.chef29.com/onmenu" ><img src="https://farm4.staticflickr.com/3782/13399873843_4180194a3e.jpg" width="225" height="250" alt="Menu"></a> 
</center>
  </div> 


  <div class="span3">
  <center>
<a href="http://www.chef29.com/how"><img src="https://farm8.staticflickr.com/7279/13400107704_bb215ac8c6.jpg" width="225" height="301" alt="howtobuy"></a>

</center>
  </div>

   <div class="span3"><center>
  <a href="http://www.chef29.com/orderpage" ><img src="https://farm4.staticflickr.com/3798/13399751675_49fea54123.jpg" width="225" height="380" alt="kart"></a>
</center>

  </div>

</div>

</center>

<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript" src="http://s.sharethis.com/loader.js"></script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44036574-1', 'chef29.com');
  ga('send', 'pageview');

</script>

<script type="text/javascript">stLight.options({publisher: "3d6bd212-1a1c-4bf7-9f1c-7154d13f873d", doNotHash: false, doNotCopy: false, hashAddressBar: true});</script>
<script>
var options={ "publisher": "3d6bd212-1a1c-4bf7-9f1c-7154d13f873d", "position": "left", "ad": { "visible": false, "openDelay": 5, "closeDelay": 0}, "chicklets": { "items": ["facebook", "twitter", "linkedin", "pinterest", "googleplus", "email", "baidu"]}};
var st_hover_widget = new sharethis.widgets.hoverbuttons(options);
</script>
</html>

app/views/categories/show.js.erb
$boxes = $('<%= j render(@pins) %>')

$('#pins').append( $boxes ).imagesLoaded( function(){
    $('#pins').masonry( 'reload');
});
<% if @pins.next_page %>
    $('.pagination').replaceWith('<%= j will_paginate(@pins) %>');
<% else %>
    $('.pagination').remove();
<% end %>