config/routes.rb
Dine::Application.routes.draw do

  resources :orderlists
  resources :shoplists
  resources :categories

  get "home/index"

  resources :pins
  resources :pin 
  
  devise_for :users
  match 'users/:id' => 'users#show', as: :user

 
  root :to => 'pins#index'
  get 'usering' => 'users#index'
  get 'detail' => 'users#detail'
  get 'manage' => 'orderlists#manage'
  get 'admin' => 'pages#admin'
  get 'return' => 'pages#return'
  get 'faq' => 'pages#faq'
  get 'why' => 'pages#why'
  get 'service' => 'pages#service'
	get 'privacy' => 'pages#privacy'
  get 'menu' => 'pages#menu'
  get 'recipies' => 'pages#recipies'  
  get 'know' => 'pages#know'
  get 'give' => 'pages#give' 
  get 'how' => 'pages#how' 
  get 'dish1' => 'pages#dish1'
  get 'dish2' => 'pages#dish2' 
  get 'dish3' => 'pages#dish3' 
  get 'dish4' => 'pages#dish4'
  get 'dish5' => 'pages#dish5' 
  get 'dish6' => 'pages#dish6'
  get 'account' => 'pages#account' 
  get 'donations' => 'pages#donations' 
  get 'delivery' => 'pages#delivery'
  get 'hunger' => 'pages#hunger'
  get 'dogood' => 'pages#dogood'
  get 'lovemeal' => 'pages#lovemeal'
  get 'help' => 'pages#help'
  get 'about' => 'pages#about'
  get 'line' => 'pages#line'
  get 'side' => 'pages#side'
  get 'fruit' => 'pages#fruit'
  get 'hocv' => 'pages#hocv'
  get 'chefs' => 'pages#chefs'
  get 'goodcompany' => 'pages#goodcompany'
  get 'hoc' => 'pages#hoc'
  get 'chef29tv' => 'pages#chef29tv'
  get 'makemoney' => 'pages#makemoney'
  get 'orderpage' => 'pages#orderpage'
  get 'pickup' => 'pages#pickup'
  get 'dogooder' => 'pages#dogooder'
  get 'onmenu' => 'pages#onmenu'

  

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  match 'alert' => 'alert#new', :as => 'alert',  :via => :get
  match 'alert'  => 'alert#create', :as => 'alert', :via => :post

  match 'wineordercontact' => 'wineordercontact#new', :as => 'wineordercontact', :via => :get
  match 'wineordercontact' => 'wineordercontact#create', :as => 'wineordercontact', :via => :post

  as :user do
  match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end
  devise_for :users, :controllers => { :confirmations => "confirmations" }

end

app/models/category.rb
class Category < ActiveRecord::Base

	attr_accessible :description, :image 
 
has_attached_file :image, styles: { large: "1400x300>"}
  validates_attachment :image, presence: true,
                            content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                            size: { less_than: 5.megabytes }
  attr_accessible :name
  has_many :pins
end

app/models/image.rb
class Image < ActiveRecord::Base
  def image_path
     "/app/public/images/#{filename}"
  end
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :description
end

app/models/orderlist.rb
class Orderlist < ActiveRecord::Base
  attr_accessible :pickupdates, :pickuplocation, :week, :month, :description, :dish1, :gift, :re, :ship, :discount, :paylater, :detail, :reciever, :account, :wireamount, :dish2, :dish3, :dish4, :dish5, :dish6, :dishsum, :time, :phone, :address
 

  belongs_to :user

  validates :dish1, presence: true
  validates :dish2, presence: true
  validates :dish3, presence: true  
  validates :dish4, presence: true
  validates :dish5, presence: true
  validates :dish6, presence: true  
  validates :week, presence: true
  validates :month, presence: true 
  
end 
 

app/models/ordernew.rb
class Ordernew

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body, :number, :item, :account, :bank, :orderid, :address, :time, :special

  validates :name, :email, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  extend FriendlyId
    friendly_id :name, use: :slugged

def should_generate_new_friendly_id?
  new_record?
end

attr_accessible :id, :description, :image, :image_remote_url, :name, :Delivery, :yt_video_id, :stop, :instaid, :instapid, :category_id, :vineid #This line won't work in Rails 4, instead, you'll have to do what I show below
  validates :image, presence: true
  validates :description, presence: true
  validates :name, presence: true
  has_attached_file :image, styles: { medium: "300x200>"}
  validates_attachment :image, content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
  size: { less_than: 5.megabytes }
  
belongs_to :user
belongs_to :category


def self.search(search)
  if search
    find(:all, :conditions => ['description LIKE ?', "%#{search}%"])
  
  else
    find(:all, order: "created_at desc")
  end
end

def image_remote_url=(url_value)
    self.image = URI.parse(url_value) unless url_value.blank?
  super
end

def video_yt_video_id=(id_value)
    self.video = URI.parse(id_value) unless id_value.blank?
  super
end
end

app/models/user.rb
class User < ActiveRecord::Base
	extend FriendlyId
  friendly_id :name, use: :slugged

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :confirmable, :rememberable, :trackable, :validatable

 has_attached_file :image, styles: { medium: "180x180>"}
 validates :address, presence: true
 validates :phone, presence: true


  # Setup accessible (or protected) attributes for your model
  attr_accessible :image, :image_file_name, :email, :password, :password_confirmation, :remember_me, :name, :address, :phone, :intro, :dish1, :dish2, :dish3
   # attr_accessible :title, :body

  has_many :pins, :dependent => :destroy
  has_many :orderlists, :dependent => :destroy

end

app/models/wineorder.rb
class Wineorder

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :phone, :wineid, :qty, :pickuplocation, :otherorder, :special, :pickupdate

  validates :name, :email, :phone, :wineid, :qty, :pickuplocation, :otherorder, :special, :pickupdate, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/helpers/alert_helper.rb
module AlertHelper
end

app/helpers/buy_helper.rb
module BuyHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/inform_helper.rb
module InformHelper
end

app/helpers/ordering_helper.rb
module OrderingHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
    def category_options
        Category.all.map{ |c| [c.name, c.id] }
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44036574-1', 'chef29.com');
  ga('send', 'pageview');

</script>

  

app/views/layouts/_header.html.erb
<div class="navbar transparent navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
             
<%= link_to "iRent1我租個", root_path, class: "brand" %>


<div class="nav-collapse">
  <ul class="nav">
   <li><div class="dropdown" style="padding:10px; display: block; "><a class="dropdown-toggle" data-toggle="dropdown" href="#" face = "Baskerville Old Face">了解更多</a>

  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel" >
   <li><%= link_to "關於我們", about_path %></li>
   <li><%= link_to "服務說明", how_path %></li>
  
   </ul>
   <li>


  <li><div class="dropdown" style="padding:10px; display: block; "><a class="dropdown-toggle" data-toggle="dropdown" href="#">台北市</a>

  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">

   <li><%= link_to "106 台北市",  'http://www.chef29.com/categories/1'%></li>
   </ul>
   
   



 </ul>
  
  <ul class="nav pull-right">
    <% if user_signed_in? %>
   
      <li><%= link_to "商品服務上架＋", new_pin_path %></li>
      <li><div class="dropdown" style="padding:10px; display: block; "><a class="dropdown-toggle" data-toggle="dropdown" href="#">個人</a>

  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
   <li><%= link_to "聯絡", contact_path %></li>
   <li><%= link_to "編輯資料", edit_user_registration_path %></li>
   <li><%= link_to "登出", destroy_user_session_path, method: :delete %></li>
  </ul>

<li> <form action="/pins" class="navbar-search pull-left"  method= "get"><input id="search" type="text" name="search" class="search-query" placeholder="搜尋"></form></li>
                                                                                  

<% else %>
  <ul class="nav pull-right">
    <li><%= link_to '訂閱',  'https://tinyletter.com/Chef29' %></li>
    <li><%= link_to '登入',  new_user_session_path %></li>
    <li><%= link_to '註冊',  new_user_registration_path %></li>
    
    <li><form action="/pins" calss="navbar-search pull-left" style="padding:5px;"  method= "get"><input id="search" type="text" name="search" class="search-query" placeholder="search"></form></li>
    
  </ul>

<% end %>

   </div>
  </div>
 </div>
</div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44036574-1', 'chef29.com');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 
<head>
  <%= @fblike %>
  <% if content_for?(:head) %>
    <%= yield(:head) %>
  <% end %>
<title> iRent1我租個－您附近所有可以租用的，名牌包，洗衣機，倒垃圾等商品服務。 </title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
</head>
  
<body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
<% end %>

<%= yield %>
    <%= render 'layouts/footer' %>
      </div>
</body>

  

<body>
  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/zh_TW/all.js#xfbml=1&appId=1421303274749826";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<script type="text/javascript">stLight.options({publisher: "3d6bd212-1a1c-4bf7-9f1c-7154d13f873d", doNotHash: false, doNotCopy: false, hashAddressBar: true});</script>

<script>
var options={ "publisher": "3d6bd212-1a1c-4bf7-9f1c-7154d13f873d", "position": "left", "ad": { "visible": false, "openDelay": 5, "closeDelay": 0}, "chicklets": { "items": ["facebook", "twitter", "linkedin", "pinterest", "email", "googleplus", "baidu", "sharethis"]}};
var st_hover_widget = new sharethis.widgets.hoverbuttons(options);
</script>

<br><br>
<hr> 

<div class="row-fluid">
  <div class="span4" style="border-right: 1px solid #ccc; " >

   <center><a href="http://www.chef29.com/give"><img src="https://farm8.staticflickr.com/7233/13537317425_37ab526249_z.jpg" width="500" height="300" alt="Kid"></a></center>
 </div>
          

<div class="span4"  >
<center>


  <br><br>  <br><br>

  <center>
  <font color="#5CA5FF" size ="6"> 訂閱 Chef29</font>
  <br><br>

  <form style="#ccc;padding:3px;text-align:center;" action="https://tinyletter.com/Chef29" method="post" target="popupwindow" onsubmit="window.open('https://tinyletter.com/Chef29', 'popupwindow', 'scrollbars=yes,width=800,height=600');return true"><label for="tlemail"> <font  size="5" face = "Baskerville Old Face"></font></label><input type="text" style="width:250px" name="email" id="tlemail" placeholder="輸入您 EMAIL 後按 ENTER!" /><input type="hidden" value="1" name="embed"/><a href="https://tinyletter.com" target="_blank"></a></form>

  </div>

  

 </center>

  <div class="span4" style="border-left: 1px solid #ccc; ">
    <center>

      <p>
    <font style="padding-left:20px;"><a href="http://www.facebook.com/pages/Chef29%E4%BB%8A%E6%99%9A%E5%A4%A7%E5%BB%9A/220639924779061" ><img src="http://farm8.staticflickr.com/7340/9910596583_6bea8cbcb7_s.jpg" width="48" height="50" alt="fb"></a></font>


    <font style="padding-left:10px;"><a href="http://instagram.com/chef29com" ><img src="http://farm3.staticflickr.com/2875/9910428935_fc0718c232_s.jpg" width="52" height="50" alt="insta"></a>
</font>


   <font style="padding-left:7px;"><a href="http://www.pinterest.com/chef29com/boards/"><img src="http://farm6.staticflickr.com/5325/9910428735_25b7e63e8f_s.jpg" width="53" height="50" alt="pintrest"></a></font>


 <font style="padding-left:10px;"><a href="https://vimeo.com/chef29/videos" ><img src="https://farm8.staticflickr.com/7442/13320883464_6c51ef8dfc_o.png" width="57" height="58" alt="twitter"></a></font>


<font style="padding-left:10px;"><img src="https://farm3.staticflickr.com/2880/13376248673_050e392bda_o.png" width="220" height="50" alt="twitter"></a></font>
<br>

  <font size="4" face = "Baskerville Old Face"> <%= link_to "Contact Us 聯絡我們",contact_path, {:style => 'color: #8c8c8c'}%></font>
    <br><br>
   <font size="4" face = "Baskerville Old Face"> <%= link_to "Service 服務條款",service_path, {:style => 'color: #8c8c8c'}%></font>
     <br><br>
   <font size="4" face = "Baskerville Old Face"><%= link_to "Privacy 隱私權政策",privacy_path, {:style => 'color: #8c8c8c'}%></font>
   <br><br>
   <font size="4" face = "Baskerville Old Face"><%= link_to "FAQs 常問問題",faq_path, {:style => 'color: #8c8c8c'}%></font>
 </center>

</div>
<br><br>

</center>
</div>
</div>
</div>


<a href="http://www.chef29.com/users/sign_up" ><img src="https://farm4.staticflickr.com/3701/13529661755_61f4350282_h.jpg" width="1451" height="300" alt="what1"></a></div>

         
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44036574-1', 'chef29.com');
  ga('send', 'pageview');

</script>
</html>